# Site settings
title: Princesse RH
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Princess RH
user_description: RH, Comptable, un peu codeuse…
user_title: Princess RH
email:
twitter_username: libellule
github_username:  libelilou
disqus_username: princesserh
repository: ""

# Build settings
markdown: kramdown

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Accueil
    url: /
  - title: Tags
    url: /tags
  - title: À propos de moi
    url: /a-propos

#Defaults
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: "_posts/princesse"
    values:
      main-class: princesse
      color: "#B31917"
  -
    scope:
      path: "_posts/rh"
    values:
      main-class: rh
      color: "#2DA0C3"
  -
    scope:
      path: "_posts/divers"
    values:
      main-class: divers
      color: "#7AAB13"
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', '.bundle', '.git', 'vendor', 'Gemfile', 'Gemfile.lock','gulpfile']
