# Site settings
title: Princesse RH
description: Mes coups de coeur de princesse, mes coups de gueule de RH !
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://libelilou.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Princesse RH
user_description: RH, Comptable, Maman… et princesse !
user_title: Princesse RH
email:
twitter_username: libellule
github_username:  libelilou
disqus_username: princesserh
repository: "Libelilou/libelilou.github.io.git"
timezone: Europe/Paris
encoding: utf-8
lang: fr

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: true

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Accueil
    url: /
  - title: Tags
    url: /tags
  - title: À propos de moi
    url: /a-propos

#Defaults
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: post
      published: true
  -
    scope:
      path: "_posts/princesse"
    values:
      main-class: princesse
      color: "#B31917"
  -
    scope:
      path: "_posts/rh"
    values:
      main-class: rh
      color: "#2DA0C3"
  -
    scope:
      path: "_posts/divers"
    values:
      main-class: divers
      color: "#7AAB13"
  -
    scope:
      path: "_posts/cuisine"
    values:
      main-class: cuisine
      color: "#EB7728"
  - scope:
      type: decks
    values:
      layout: deck
      theme: clever
      transition: fade
  - scope:
      type: slides
    values:
      layout: slide
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', '.bundle', '.git', 'vendor', 'Gemfile', 'Gemfile.lock','gulpfile']

collections:
  slides :
    output: true
    permalink: /:path/
  decks :
    output: true
    permalink: /:path/
